version: '2'
services:
    db:
        image: mysql
        hostname: mysql
        container_name: gatedb
        environment:
            MYSQL_ROOT_PASSWORD: gate
            MYSQL_USER: gate
            MYSQL_PASSWORD: gate
    app:
        build: .
        hostname: app
        container_name: gateapp
        environment:
            BASEDIR: /trunk/tomcat6
            CATALINA_HOME: /trunk/tomcat6
        depends_on:
            - db
        links:
            - db:mysql
        tty: true
        stdin_open: true
