version: '2'
services:
  gate:
    build: .
    container_name: gateapp
    #volumes:
    # - .:/code
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: somepassword
        HOSTNAME: gateapp
    ports:
      - "8080:8080"
    #restart: always
    tty: true
    stdin_open: true
